spring:
  application:
    name: befintax
app:
  market-data:
    twelve-data:
      key: a8b2b707148b4b7fa892efeeb4c68ebc
  cors:
    allowed-origins: http://localhost:4200,https://www.befintax.be,https://befintax.be
logging:
      level:
        be.lpbconsult.befintax: DEBUG
        org.springframework.security: INFO