spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/befintax}
    username: ${SPRING_DATASOURCE_USERNAME:befintax}
    password: ${SPRING_DATASOURCE_PASSWORD:SFGRe35f6hHj}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/befintax
          jwk-set-uri: http://localhost:8081/realms/befintax/protocol/openid-connect/certs